const SUPABASE_URL = "https://yaauwnvcjjetdybeixfr.supabase.co";
const SUPABASE_KEY = "sb_publishable_POH2JdWG0JMCzEkt9lhrPg_SmLG0Y1I";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const symbols = { p:"♟",r:"♜",n:"♞",b:"♝",q:"♛",k:"♚",P:"♙",R:"♖",N:"♘",B:"♗",Q:"♕",K:"♔" };
const chess = new Chess();
const $ = (id) => document.getElementById(id);
const board = $("board"), status = $("status"), error = $("roomError");
const start = $("startScreen"), playerMode = $("playerModeScreen"), computer = $("computerScreen"), room = $("roomScreen"), lobby = $("lobbyScreen"), game = $("gameScreen");
const codeDisplay = $("roomCodeDisplay"), connection = $("connectionStatus"), lobbyError = $("lobbyError"), lobbyPlayers = $("lobbyPlayers"), startPrivate = $("startPrivateBtn"), undo = $("undoBtn");
const files = ["a","b","c","d","e","f","g","h"], ranks = ["8","7","6","5","4","3","2","1"];
let selected = null, lastMove = null, channel = null, privateRoom = false, computerMode = false, thinking = false, difficulty = "medium", color = null, host = false, started = false, undoState = null;
const id = crypto.randomUUID();

function show(screen) { [start, playerMode, computer, room, lobby, game].forEach((item) => item.classList.add("hidden")); screen.classList.remove("hidden"); }
function draw() {
  document.querySelectorAll(".square").forEach((square) => { square.innerHTML = ""; square.classList.remove("selected","highlighted","last-move"); });
  chess.board().forEach((row, r) => row.forEach((piece, f) => { if (!piece) return; const el = $(files[f] + ranks[r]); const span = document.createElement("span"); span.className = `piece ${piece.color}`; span.textContent = symbols[piece.color === "w" ? piece.type.toUpperCase() : piece.type]; el.appendChild(span); }));
  if (lastMove) { $(lastMove.from)?.classList.add("last-move"); $(lastMove.to)?.classList.add("last-move"); }
  status.textContent = chess.game_over() ? (chess.in_checkmate() ? "Checkmate! Game over." : "Game over: Draw!") : `${chess.turn() === "w" ? "White" : "Black"}'s turn${chess.in_check() ? " (Check!)" : ""}`;
  board.classList.toggle("flipped", privateRoom ? color === "b" : !computerMode && chess.turn() === "b");
}
function buildBoard() { board.innerHTML = ""; for (let r=0;r<8;r++) for (let f=0;f<8;f++) { const square = document.createElement("div"); square.className = `square ${(r+f)%2 ? "dark" : "light"}`; square.id = files[f]+ranks[r]; square.onclick = () => clickSquare(square.id); board.appendChild(square); } draw(); }
async function clickSquare(square) {
  if (chess.game_over() || thinking || (computerMode && chess.turn() !== "w")) return;
  if (selected) {
    if (selected === square) { selected = null; draw(); return; }
    const previous = computerMode ? { fen: chess.fen(), lastMove } : null;
    const move = chess.move({ from: selected, to: square, promotion: "q" });
    if (move) { selected = null; lastMove = { from: move.from, to: move.to }; if (computerMode) undoState = previous; if (privateRoom) await channel.send({ type:"broadcast", event:"move", payload:{ fen:chess.fen(), from:move.from, to:move.to } }); draw(); if (computerMode && !chess.game_over()) computerMove(); return; }
  }
  const piece = chess.get(square);
  if (piece && piece.color === chess.turn() && (!privateRoom || piece.color === color)) { selected = square; draw(); $(square).classList.add("selected"); chess.moves({ square, verbose:true }).forEach((move) => $(move.to).classList.add("highlighted")); } else { selected = null; draw(); }
}
function startLocal() { privateRoom=false; computerMode=false; thinking=false; color=null; undo.classList.add("hidden"); codeDisplay.textContent="LOCAL"; connection.textContent="Pass & Play"; chess.reset(); lastMove=null; selected=null; draw(); show(game); }
function startComputer(level) { privateRoom=false; computerMode=true; thinking=false; difficulty=level; color="w"; undo.classList.remove("hidden"); codeDisplay.textContent="COMPUTER"; connection.textContent=`Computer: ${level}`; chess.reset(); lastMove=null; undoState=null; selected=null; draw(); show(game); }
function evaluate(position) { const values={p:100,n:320,b:330,r:500,q:900,k:20000}; return position.board().flat().reduce((score,p) => p ? score + values[p.type]*(p.color === "b" ? 1 : -1) : score, 0); }
function chooseComputerMove() { const moves=chess.moves({verbose:true}); if(difficulty==="easy") return moves[Math.floor(Math.random()*moves.length)]; if(difficulty==="medium") { const captures=moves.filter((move)=>move.captured); const pool=captures.length?captures:moves; return pool[Math.floor(Math.random()*pool.length)]; } let best=moves[0], score=-Infinity; moves.forEach((move)=>{ const test=new Chess(chess.fen()); test.move({from:move.from,to:move.to,promotion:"q"}); const value=evaluate(test); if(value>score){score=value;best=move;} }); return best; }
function computerMove() { thinking=true; connection.textContent="Computer is thinking..."; setTimeout(() => { if (!computerMode || chess.game_over()) return; const move=chooseComputerMove(); chess.move({from:move.from,to:move.to,promotion:"q"}); lastMove={from:move.from,to:move.to}; thinking=false; connection.textContent=`Computer: ${difficulty}`; draw(); }, 300); }
function undoComputerTurn() { if (!undoState || thinking) return; chess.load(undoState.fen); lastMove=undoState.lastMove; undoState=null; selected=null; draw(); }
function players() { return Object.values(channel.presenceState()).flat(); }
function updateLobby() { const list=players(); lobbyPlayers.textContent=list.length===2?"Both players connected. Choose your sides.":"Waiting for an opponent..."; startPrivate.classList.toggle("hidden",!host || list.length!==2 || !list.every((p)=>p.color) || list[0].color===list[1].color); document.querySelectorAll(".side-option").forEach((button)=>{ const taken=list.some((p)=>p.playerId!==id&&p.color===button.dataset.color); button.disabled=taken; button.classList.toggle("selected",color===button.dataset.color); }); }
async function selectSide(next) { const opponent=players().find((p)=>p.playerId!==id); if(opponent?.color===next){lobbyError.textContent="Your opponent has already chosen that side.";return;} color=next; lobbyError.textContent=""; await channel.track({playerId:id,color}); updateLobby(); }
function enterGame() { started=true; connection.textContent=`Connected as ${color === "w" ? "White" : "Black"}`; chess.reset(); lastMove=null; selected=null; draw(); show(game); }
async function leavePrivate(notify=false) { if(channel){if(notify) await channel.send({type:"broadcast",event:"player-left"}); await channel.unsubscribe();channel=null;} privateRoom=false;started=false;color=null;show(start); }
async function joinPrivate(code, isHost) { privateRoom=true; computerMode=false; host=isHost; started=false;color=null; codeDisplay.textContent=code; $("lobbyCodeDisplay").textContent=code; $("undoBtn").classList.add("hidden"); show(lobby); channel=supabaseClient.channel(`chess-room-${code}`,{config:{presence:{key:id},broadcast:{self:false}}}); channel.on("presence",{event:"sync"},updateLobby).on("presence",{event:"leave"},function(presence){const key=presence.key;if(key!==id&&started){alert("Your opponent left the game.");leavePrivate();}else updateLobby();}).on("broadcast",{event:"player-left"},function(){if(started){alert("Your opponent left the game.");leavePrivate();}}).on("broadcast",{event:"start"},function(message){const payload=message.payload;if(payload.colors[id]){color=payload.colors[id];enterGame();}}).on("broadcast",{event:"move"},function(message){const payload=message.payload;chess.load(payload.fen);lastMove=payload.from?{from:payload.from,to:payload.to}:null;draw();}).on("broadcast",{event:"new-game"},function(){started=false;color=null;chess.reset();lastMove=null;show(lobby);channel.track({playerId:id,color:null});updateLobby();}); channel.subscribe(async function(state){if(state==="SUBSCRIBED"){if(players().length>=2){lobbyError.textContent="This room already has two players.";await leavePrivate();return;}await channel.track({playerId:id,color:null});updateLobby();}}); }

$("computerModeBtn").onclick=()=>show(computer); $("playerModeBtn").onclick=()=>show(playerMode); $("backToStartBtn").onclick=()=>show(start); $("backFromComputerBtn").onclick=()=>show(start); $("localModeBtn").onclick=startLocal; $("privateModeBtn").onclick=()=>show(room); $("undoBtn").onclick=undoComputerTurn;
document.querySelectorAll(".difficulty-option").forEach((button)=>button.onclick=()=>startComputer(button.dataset.difficulty));
$("createRoomBtn").onclick=async()=>{const code=Math.random().toString(36).slice(2,8).toUpperCase();const result=await supabaseClient.from("chess_rooms").insert({code});if(result.error){error.textContent="Could not create the room. Check Supabase setup.";return;}joinPrivate(code,true);};
$("showJoinBtn").onclick=()=>{$("createRoomPanel").classList.add("hidden");$("joinRoomPanel").classList.remove("hidden");$("roomInput").focus();}; $("backBtn").onclick=()=>show(start); $("leaveLobbyBtn").onclick=()=>leavePrivate(); $("leaveBtn").onclick=()=>leavePrivate(true); $("startPrivateBtn").onclick=async()=>{const list=players();const colors=Object.fromEntries(list.map((p)=>[p.playerId,p.color]));await channel.send({type:"broadcast",event:"start",payload:{colors}});enterGame();};
$("joinRoomPanel").onsubmit=async(e)=>{e.preventDefault();const code=$("roomInput").value.trim().toUpperCase();const result=await supabaseClient.from("chess_rooms").select("code").eq("code",code).maybeSingle();if(result.error||!result.data){error.textContent="That room does not exist.";return;}joinPrivate(code,false);}; $("resetBtn").onclick=async()=>{if(privateRoom){await channel.send({type:"broadcast",event:"new-game"});started=false;color=null;show(lobby);await channel.track({playerId:id,color:null});updateLobby();return;}chess.reset();lastMove=null;undoState=null;thinking=false;draw();}; window.addEventListener("pagehide",()=>channel&&supabaseClient.removeChannel(channel)); buildBoard();